# wrangler.toml
name = "sk-cf-env-vars"
compatibility_date = "2024-04-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
PUBLIC_VAR = "Runtime env var goes here"
PUBLIC_STATIC_VAR = "Build time env var goes here"